version: '3.8'

services:
  stokio-db:
    image: postgres:14
    container_name: stokio-db
    ports:
      - "5432:5432"
    volumes:
      - stokio-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=stokio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

volumes:
  stokio-data: